# Generated by Django 6.0.7 on 2026-08-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.BooleanField(default=True),
        ),
    ]
