# Generated by Django 6.0.7 on 2026-08-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
    ]
